name: takeout_mobile
description: Takeout
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  takeout_lib:
    path: ../takeout_lib/
  cupertino_icons: ^1.0.6
  dynamic_color: ^1.6.9
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  json_annotation: ^4.8.1
  logging: ^1.2.0
  nested: ^1.0.0
  recase: ^4.1.0
  receive_intent: ^0.2.4
  rxdart: ^0.27.7
  timeago: ^3.6.0
  timeago_flutter: ^3.6.0
  url_launcher: ^6.2.2
  video_player: ^2.8.1
  wakelock_plus: ^1.1.4
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
