name: takeout_mobile
description: TakeoutFM
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  takeout_lib:
    path: ../takeout_lib/
  cupertino_icons: ^1.0.8
  dynamic_color: ^1.7.0
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  nested: ^1.0.0
  recase: ^4.1.0
  receive_intent: ^0.2.5
  rxdart: ^0.28.0
  timeago: ^3.6.1
  timeago_flutter: ^3.6.0
  url_launcher: ^6.3.0
  video_player: ^2.9.1
  wakelock_plus: ^1.2.5
  webview_flutter: ^4.8.0
  audio_service: ^0.18.18
  swipeable_tile: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
