name: takeout_lib
description: TakeoutFM Library
version: 0.12.0
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  audio_service: ^0.18.13
  audio_session: ^0.1.19
  cached_network_image: ^3.3.1
  chewie: ^1.7.5
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  bloc: 8.1.3
  flutter_bloc: ^8.1.4
  hydrated_bloc: ^9.1.4
  logging: ^1.2.0
  json_annotation: ^4.8.1
  just_audio: ^0.9.37
  palette_generator: ^0.3.3+3
  path_provider: ^2.1.2
  receive_intent: ^0.2.5
  rxdart: ^0.27.7
  video_player: ^2.8.3
  listenbrainz_dart: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
