name: takeout_lib
description: TakeoutFM Library
version: 0.18.1 # #version#
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  audio_service: ^0.18.15
  audio_session: ^0.1.21
  cached_network_image: ^3.3.1
  chewie: ^1.8.1
  connectivity_plus: ^5.0.2
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  bloc: 8.1.4
  flutter_bloc: ^8.1.6
  flutter_cache_manager: ^3.3.2
  http: ^1.2.1
  hydrated_bloc: ^9.1.5
  logging: ^1.2.0
  json_annotation: ^4.9.0
  just_audio: ^0.9.38
  nested: ^1.0.0
  octo_image: ^2.0.0
  palette_generator: ^0.3.3+3
  path: ^1.9.0
  path_provider: ^2.1.3
  receive_intent: ^0.2.5
  rxdart: ^0.27.7
  video_player: ^2.9.1
  listenbrainz_dart: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
