name: takeout_watch
description: TakeoutFM
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  takeout_lib:
    path: ../takeout_lib/
  android_intent_plus: ^4.0.3
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  nested: ^1.0.0
  device_info_plus: ^9.1.2
  percent_indicator: ^4.2.3
  rotary_scrollbar: ^1.0.0
  timeago: ^3.6.1
  wear_plus: ^1.2.0
  wearable_rotary: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
