name: takeout_watch
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  takeout_lib:
    path: ../takeout_lib/
  android_intent_plus: ^4.0.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  cupertino_icons: ^1.0.6
  nested: ^1.0.0
  device_info_plus: ^9.0.1
  percent_indicator: ^4.2.3
  rotary_scrollbar: ^0.1.1
  timeago: ^3.1.0
  wear: ^1.1.0
  wearable_rotary: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
